test:
  domain: localhost

development:
  domain: "localhost:3000"

production:
  # domain: "canvas.example.com"
  domain: <%= ENV['CANVAS_DOMAIN'] %>
  # whether this instance of canvas is served over ssl (https) or not
  # defaults to true for production, false for test/development
  ssl: false
  # files_domain: "canvasfiles.example.com"
